webapp/user/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from webapp.db import db


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    password = db.Column(db.String(128))
    role = db.Column(db.String(10), index=True)
    email = db.Column(db.String(50))

    @property
    def is_admin(self):
        return self.role == 'admin'

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def __repr__(self):
        return '<User name = {}, id = {}>'.format(self.username, self.id)

webapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError

from webapp.user.models import User


class LoginForm(FlaskForm):
    username = StringField('Имя пользователя', validators=[DataRequired()], render_kw={"class": "form-control"})
    password = PasswordField('Пароль', validators=[DataRequired()], render_kw={"class": "form-control"})
    remember_me = BooleanField('Запомнить меня', default=True, render_kw={"class": "form-check-input"})
    submit = SubmitField('Отправить', render_kw={"class": "btn btn-primary"})


class RegistrationForm(FlaskForm):
    username = StringField('Имя пользователя', validators=[DataRequired()], render_kw={"class": "form-control"})
    email = StringField('Email', validators=[DataRequired(), Email()], render_kw={"class": "form-control"})
    password = PasswordField('Пароль', validators=[DataRequired()], render_kw={"class": "form-control"})
    password2 = PasswordField('Повторите пароль', validators=[DataRequired(), EqualTo('password')],
                              render_kw={"class": "form-control"})
    submit = SubmitField('Отправить!', render_kw={"class": "btn btn-primary"})

    def validate_username(self, username):
        users_count = User.query.filter_by(username=username.data).count()
        if users_count > 0:
            raise ValidationError('Пользователь с таким именем уже зарегистрирован')

    def validate_email(self, email):
        users_count = User.query.filter_by(email=email.data).count()
        if users_count > 0:
            raise ValidationError('Пользователь с такой электронной почтой уже зарегистрирован')

webapp/user/views.py
from flask import render_template, flash, redirect, url_for, Blueprint
from flask_login import current_user, login_user, logout_user

from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User
from webapp.db import db
from webapp.utils import get_redirect_target

blueprint = Blueprint('user', __name__, url_prefix='/users')


@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(get_redirect_target())
    title = "Авторизация"
    login_form = LoginForm()
    return render_template('user/login.html', page_title=title, form=login_form)


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('Вы вошли на сайт')
            return redirect(get_redirect_target())

    flash('Неправильное имя пользователя или пароль')
    return redirect(url_for('user.login'))


@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Вы успешно разлогинились')
    return redirect(get_redirect_target())


@blueprint.route('/register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('ads.index'))
    form = RegistrationForm()
    title = "Регистрация"
    return render_template('user/registration.html', page_title=title, form=form)


@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, role='user')
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Вы успешно зарегистрировались!')
        return redirect(url_for('user.login', next='/'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Ошибка в поле "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
        return redirect(url_for('user.register'))
    flash('Пожалуйста, исправьте ошибки в форме')
    return redirect(url_for('user.register'))

webapp/templates/user/login.html
    {% extends "base.html" %}

    {% block content %}
        <div id="content">
            <h1 style="text-align: center">{{ page_title }}</h1>
            <div class="ads">
                <div class="col-4">
                    {% with messages = get_flashed_messages() %}
                        {% if messages %}
                        <div class="alert alert-warning" role="alert">
                            {% for message in messages %}
                                {{ message }}<br>
                            {% endfor %}
                        </div>
                        {% endif %}
                    {% endwith %}
                    <form action="{{ url_for('user.process_login') }}" method="post">
                        {{ form.hidden_tag() }}
                        <div class="form-group">
                            {{ form.username.label }}<br>
                            {{ form.username() }}
                        </div>
                        <div class="form-group">
                            {{ form.password.label }}<br>
                            {{ form.password() }}
                        </div>
                        <div class="form-group form-check">
                            {{ form.remember_me() }}
                            {{ form.remember_me.label(class_='form-check-label') }}
                        </div>
                        {{ form.submit }}
                    </form>
                </div>

            </div>
        </div>
    {% endblock %}

webapp/templates/user/registration.html
    {% extends "base.html" %}

    {% block content %}
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <div id="content">
            <h1 style="text-align: center">{{ page_title }}</h1>
            <div class="ads">
                <div class="col-4">

                    <form action="{{ url_for('user.process_reg') }}" method="post">
                        {{ form.hidden_tag() }}
                        <div class="form-group">
                            {{ form.username.label }}<br>
                            {{ form.username() }}
                        </div>
                        <div class="form-group">
                            {{ form.email.label }}<br>
                            {{ form.email() }}
                        </div>
                        <div class="form-group">
                            {{ form.password.label }}<br>
                            {{ form.password() }}
                        </div>
                        <div class="form-group">
                            {{ form.password2.label }}<br>
                            {{ form.password2() }}
                        </div>
                        {{ form.submit }}
                    </form>
                </div>

            </div>
        </div>
    {% endblock %}