webapp/admin/views.py
from flask import Blueprint, render_template
from webapp.user.decorators import admin_required


blueprint = Blueprint('admin', __name__, url_prefix='/admin')


@blueprint.route('/')
@admin_required
def admin_index():
    title = "Панель управления"
    return render_template('admin/index.html', page_title=title)

webapp/ads/views.py
from flask import abort, Blueprint, flash, current_app, render_template, redirect, request
from flask_login import current_user, login_required

from webapp.db import db
from webapp.ads.forms import CommentForm
from webapp.ads.models import Comment, Ads
from webapp.utils import get_redirect_target

blueprint = Blueprint('ads', __name__)


@blueprint.route('/', methods=['POST', 'GET'])
def index(page=1):
    pg = request.args.get('page', '')
    if pg:
        page = int(pg)
    else:
        page = 1
    print(f'page = {pg}')
    page_title = "Продажа рептилий и террариумов в России"
    ads_list = Ads.query.filter(Ads.text.isnot(None)).order_by(Ads.published.desc()).paginate(page, current_app.config[
        "POSTS_PER_PAGE"], False)

    return render_template('ads/index.html', page_title=page_title, ads_list=ads_list)


@blueprint.route('/ads/<int:ads_id>')
def single_ad(ads_id):
    my_ad = Ads.query.filter(Ads.id == ads_id).first()

    if not my_ad:
        abort(404)
    comment_form = CommentForm(ad_id=my_ad.id)
    return render_template('ads/single_ad.html', ad=my_ad,  comment_form=comment_form)


@blueprint.route('/ads/comment', methods=['POST'])
@login_required
def add_comment():
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(text=form.comment_text.data, ads_id=form.ad_id.data, user_id=current_user.id)
        db.session.add(comment)
        db.session.commit()
        flash('Комментарий успешно добавлен')
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Ошибка в заполнении поля "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
    return redirect(get_redirect_target())

webapp/user/views.py
from flask import render_template, flash, redirect, url_for, Blueprint
from flask_login import current_user, login_user, logout_user

from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User
from webapp.db import db
from webapp.utils import get_redirect_target

blueprint = Blueprint('user', __name__, url_prefix='/users')


@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(get_redirect_target())
    title = "Авторизация"
    login_form = LoginForm()
    return render_template('user/login.html', page_title=title, form=login_form)


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('Вы вошли на сайт')
            return redirect(get_redirect_target())

    flash('Неправильное имя пользователя или пароль')
    return redirect(url_for('user.login'))


@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Вы успешно разлогинились')
    return redirect(get_redirect_target())


@blueprint.route('/register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('ads.index'))
    form = RegistrationForm()
    title = "Регистрация"
    return render_template('user/registration.html', page_title=title, form=form)


@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, role='user')
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Вы успешно зарегистрировались!')
        return redirect(url_for('user.login', next='/'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Ошибка в поле "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
        return redirect(url_for('user.register'))
    flash('Пожалуйста, исправьте ошибки в форме')
    return redirect(url_for('user.register'))

webapp/templates/base.html
<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSS -->
    <link href="/static/style.css" rel="stylesheet" type="text/css">
    <link href="/static/bootstrap.css" rel="stylesheet" type="text/css">
    <title>{{ page_title }}</title>
</head>

<body>
    <div id="wrapper">
        <div id="header">
            <div id="logo">
                <h3 class="slogan">Гады России</h3>
            </div>
            <div class="weather">
                {% if weather %}
                <span class="weather">Погода в Москве: температура {{ weather.temp_C }}, ощущается как {{ weather.FeelsLikeC }}</span>
                {% else %}
                Сервис погоды временно недоступен
                {% endif %}
            </div>
        </div>
        {% include 'menu.html' %}
        {% block content %}{% endblock %}
        <div id="footer">

        </div>
    </div>
</body>

</html>

webapp/templates/index.html
<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSS -->
    <link href="/static/style.css" rel="stylesheet" type="text/css">
    <title>{{ page_title }}</title>
</head>

<body>
    <div id="wrapper">
        <div id="header">
            <div id="logo">
                <h3 class="slogan">Гады России</h3>
            </div>
            <div class="weather">
                {% if weather %}
                <span class="weather">Погода в Москве: температура {{ weather.temp_C }}, ощущается как {{ weather.FeelsLikeC }}</span>
                {% else %}
                Сервис погоды временно недоступен
                {% endif %}
            </div>
        </div>
        <div id="content">
            <h1 style="text-align: center">{{ page_title }}</h1>
            <div class="ads">
                {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="alert alert-warning" role="alert">
                    {% for message in messages %}
                    {{ message }}<br>
                    {% endfor %}
                </div>
                {% endif %}
                {% endwith %}

                {% for ad in ads_list.items %}
                <div class="ad">
                    <!-- ads.url и ads.title - ссылка на объявление и его  заголовок  -->
                    <div class="ad_photo" data-marker="item-photo">
                        <!-- img.src - ссылка на картинку -->
                        <img src="{{ ad.first_image_src }}" />
                    </div>
                    <div class="ad_data">
                        <h3>{{ ad.title }}</h3>
                        <span>{{'Цена: ' + ad.price|string  + ' ₽' }}</span><br>
                         <span class="adr">{{ ad.address}}</span><br>
                        <!-- ads.published - дата публикации -->
                        <span>{{ ad.published.strftime("%d.%m.%Y %H:%M") }}</span>
                    </div>
                </div>
                <hr />
                {% endfor %}
                <!-- экспериментируем с пагинацией -->
                <div class="pag_exp">
                    <h6>prev_num = {{ ads_list.prev_num }}</h6>
                    <h6>next_num = {{ ads_list.next_num }}</h6>
                </div>
                <div class="pagination">
                    {% if ads_list.has_prev %}<a href="{{ url_for('ads.index', page = ads_list.prev_num) }}">
                        << Назад</a>{% else %}<< Назад{% endif %} | {% if ads_list.has_next %}<a href="{{ url_for('ads.index', page = ads_list.next_num) }}">Вперёд >>
                    </a>{% else %}Вперёд >>{% endif %}
                </div>
            </div>
        </div>
        <div id="footer">

        </div>
    </div>
</body>

</html>

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Главная страница <span class="sr-only">(current)</span></a>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Поиск" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
    </form>
    <ul class="navbar-nav">
      {% if current_user.is_authenticated %}
        <li class="nav-item">
            <span class="nav-link">Привет, {{ current_user.username }}!</span>
        </li>
        {% if current_user.is_admin %}
          <li class="nav-item">
              <a href="{{ url_for('admin.admin_index') }}" class="nav-link">Админка</a>
          </li>
        {% endif %}
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.logout') }}">Выйти</a>
        </li>
      {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.login', next=request.full_path) }}">Войти</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.register') }}">Регистрация</a>
        </li>
      {% endif %}

    </ul>
  </div>
</nav>

webapp/templates/messages.html
{% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="alert alert-warning" role="alert">
        {% for message in messages %}
            {{ message }}<br>
        {% endfor %}
    </div>
    {% endif %}
{% endwith %}