webapp/ads/models.py
from sqlalchemy.orm import relationship

from webapp.db import db

from datetime import datetime


class Ads(db.Model):
    id = db.Column(db.Integer, primary_key=True, unique=True, autoincrement=True, nullable=False)
    title = db.Column(db.String, nullable=False)
    url = db.Column(db.String, unique=True, nullable=False)
    price = db.Column(db.Integer, default=0)
    address = db.Column(db.String)
    published = db.Column(db.DateTime, nullable=False, default=datetime.now())
    text = db.Column(db.Text)
    images = db.relationship("Img", backref="img_src")

    @property
    def first_image_src(self):
        if self.images:
            return self.images[0].src
        return ""

    @property
    def all_ads_images_src(self):
        if self.images:
            return [img.src for img in self.images]
        return []

    @staticmethod
    def img_src_for_ad_id(id_):

        res = []
        for ad in Ads.query.all():
            for im in ad.images:
                if im.ad_id == id_:
                    res.append(im.src)
        return res

    def comments_count(self):
        return Comment.query.filter(Comment.ads_id == self.id).count()

    def __repr__(self):
        return 'Ads {} {}>'.format(self.title, self.url)


class Img(db.Model):
    id = db.Column(db.Integer, primary_key=True, unique=True, autoincrement=True, nullable=False)
    alt = db.Column(db.String, nullable=False)
    src = db.Column(db.String, unique=False, nullable=False)
    ad_id = db.Column(db.Integer, db.ForeignKey('ads.id', ondelete='SET NULL'))

    def __repr__(self):
        return 'Image {} {}>'.format(self.alt, self.src)


class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.Text, nullable=False)
    created = db.Column(db.DateTime, nullable=False, default=datetime.now())
    ads_id = db.Column(
        db.Integer,
        db.ForeignKey('ads.id', ondelete='CASCADE'),
        index=True
    )
    user_id = db.Column(
        db.Integer,
        db.ForeignKey('user.id', ondelete='CASCADE'),
        index=True
    )
    ads = relationship('Ads', backref='comments')
    user = relationship('User', backref='comments')

    def __repr__(self):
        return '<Comment {}>'.format(self.id)

webapp/ads/forms.py
from flask_wtf import FlaskForm
from wtforms import HiddenField, StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError

from webapp.ads.models import Ads


class CommentForm(FlaskForm):
    ad_id = HiddenField('ID объявления', validators=[DataRequired()])
    comment_text = StringField('Текст комментария', validators=[DataRequired()], render_kw={"class": "form-control"})
    submit = SubmitField('Отправить!', render_kw={"class": "btn btn-primary"})

    def validate_ad_id(self, ad_id):
        if not Ads.query.get(ad_id.data):
            raise ValidationError('Вы пытаетесь прокомментировать объявление с несуществующим id')

webapp/ads/views.py
from flask import abort, Blueprint, flash, current_app, render_template, redirect, request
from flask_login import current_user, login_required

from webapp.db import db
from webapp.ads.forms import CommentForm
from webapp.ads.models import Comment, Ads
from webapp.utils import get_redirect_target

blueprint = Blueprint('ads', __name__)


@blueprint.route('/', methods=['POST', 'GET'])
def index(page=1):
    pg = request.args.get('page', '')
    if pg:
        page = int(pg)
    else:
        page = 1
    print(f'page = {pg}')
    page_title = "Продажа рептилий и террариумов в России"
    ads_list = Ads.query.filter(Ads.text.isnot(None)).order_by(Ads.published.desc()).paginate(page, current_app.config[
        "POSTS_PER_PAGE"], False)

    return render_template('ads/index.html', page_title=page_title, ads_list=ads_list)


@blueprint.route('/ads/<int:ads_id>')
def single_ad(ads_id):
    my_ad = Ads.query.filter(Ads.id == ads_id).first()

    if not my_ad:
        abort(404)
    comment_form = CommentForm(ad_id=my_ad.id)
    return render_template('ads/single_ad.html', ad=my_ad,  comment_form=comment_form)


@blueprint.route('/ads/comment', methods=['POST'])
@login_required
def add_comment():
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(text=form.comment_text.data, ads_id=form.ad_id.data, user_id=current_user.id)
        db.session.add(comment)
        db.session.commit()
        flash('Комментарий успешно добавлен')
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Ошибка в заполнении поля "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
    return redirect(get_redirect_target())

webapp/templates/ads/index.html
    {% extends "base.html" %}

    {% block content %}
        <div id="content">
            <div class="ads">
                {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="alert alert-warning" role="alert">
                    {% for message in messages %}
                    {{ message }}<br>
                    {% endfor %}
                </div>
                {% endif %}
                {% endwith %}

                {% for ad in ads_list.items %}
                <div class="ad">
                    <!-- ads.url и ads.title - ссылка на объявление и его  заголовок  -->
                    <div class="ad_photo" data-marker="item-photo">
                        <!-- img.src - ссылка на картинку -->
                        <img src="{{ ad.first_image_src }}" />
                    </div>
                    <div class="ad_data">
                        <h3><a href="{{ url_for('ads.single_ad', ads_id=ad.id) }}">{{ ad.title }}</a></h3>
                        <span>{{'Цена: ' + ad.price|string  + ' ₽' }}</span><br>
                         <span class="adr">{{ ad.address}}</span><br>
                        <!-- ads.published - дата публикации -->
                        <span>{{ ad.published.strftime("%d.%m.%Y %H:%M") }} | Комментарии: {{ ad.comments_count() }}</span>
                    </div>
                </div>
                <hr />
                {% endfor %}
                <!-- экспериментируем с пагинацией -->
                <div class="pag_exp">
                    <h6>prev_num = {{ ads_list.prev_num }}</h6>
                    <h6>next_num = {{ ads_list.next_num }}</h6>
                </div>
                <div class="pgn">
                    {% if ads_list.has_prev %}<a href="{{ url_for('ads.index', page = ads_list.prev_num) }}">
                        << Назад</a>{% else %}<< Назад{% endif %}  |  {% if ads_list.has_next %}<a href="{{ url_for('ads.index', page = ads_list.next_num) }}">Вперёд >>
                    </a>{% else %}Вперёд >>{% endif %}
                </div>
            </div>
        </div>
    {% endblock %}

webapp/templates/ads/single_ad.html
{% extends "content_base.html" %}

{% block content %}
    <div class="item-view-content'">
        {% include('messages.html') %}
        {{ ad.text|safe }}
        {% if ad.comments %}
            <h3>Комментарии:</h3>
            {% for comment in ad.comments %}
            <div class="card">
                <div class="card-body">
                    <p class="card-text">{{ comment.text }}</p>
                    <p class="card-text">
                        <small>Опубликовано: {{ comment.created.strftime('%d.%m.%Y') }} |
                            Автор: {{ comment.user.username }}</small>
                    </p>
                </div>
            </div>
            {% endfor %}
        {% endif %}
        {% if current_user.is_authenticated %}
            <form action="{{ url_for('ads.add_comment') }}" method="POST">
                {{ comment_form.hidden_tag() }}
                <div class="form-group">
                    {{ comment_form.comment_text.label }}
                    {{ comment_form.comment_text() }}
                </div>
                {{ comment_form.submit() }}
            </form>
        {% else %}
            <p><a href="{{ url_for('user.login', next=request.full_path) }}">Авторизуйтесь</a>, чтобы комментировать</p>
        {% endif %}
    </div><br><br>
{% endblock %}